# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'argo.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(572, 417)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 551, 351))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 110, 531, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.text_Dest = QtWidgets.QTextBrowser(self.layoutWidget)
        self.text_Dest.setObjectName("text_Dest")
        self.gridLayout.addWidget(self.text_Dest, 1, 1, 1, 1)
        self.label_Source = QtWidgets.QLabel(self.layoutWidget)
        self.label_Source.setObjectName("label_Source")
        self.gridLayout.addWidget(self.label_Source, 0, 0, 1, 1)
        self.pushButton_SB = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_SB.setObjectName("pushButton_SB")
        self.gridLayout.addWidget(self.pushButton_SB, 0, 2, 1, 1)
        self.pushButton_DB = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_DB.setObjectName("pushButton_DB")
        self.gridLayout.addWidget(self.pushButton_DB, 1, 2, 1, 1)
        self.labels_Destination = QtWidgets.QLabel(self.layoutWidget)
        self.labels_Destination.setObjectName("labels_Destination")
        self.gridLayout.addWidget(self.labels_Destination, 1, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget)
        self.progressBar.setAutoFillBackground(True)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 2, 1, 1, 1)
        self.text_Source = QtWidgets.QTextBrowser(self.layoutWidget)
        self.text_Source.setObjectName("text_Source")
        self.gridLayout.addWidget(self.text_Source, 0, 1, 1, 1)
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(360, 250, 178, 31))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Abort = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_Abort.setObjectName("pushButton_Abort")
        self.horizontalLayout.addWidget(self.pushButton_Abort)
        self.pushButton_OK = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_OK.setObjectName("pushButton_OK")
        self.horizontalLayout.addWidget(self.pushButton_OK)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(20, 40, 511, 231))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_Mir = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Mir.setCheckable(True)
        self.checkBox_Mir.setChecked(True)
        self.checkBox_Mir.setObjectName("checkBox_Mir")
        self.gridLayout_2.addWidget(self.checkBox_Mir, 0, 0, 1, 1)
        self.checkBox_Skip = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Skip.setEnabled(True)
        self.checkBox_Skip.setChecked(True)
        self.checkBox_Skip.setObjectName("checkBox_Skip")
        self.gridLayout_2.addWidget(self.checkBox_Skip, 0, 1, 1, 1)
        self.checkBox_Verb = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Verb.setEnabled(False)
        self.checkBox_Verb.setObjectName("checkBox_Verb")
        self.gridLayout_2.addWidget(self.checkBox_Verb, 1, 0, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_3.setEnabled(False)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_2.addWidget(self.checkBox_3, 1, 1, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_6.setEnabled(False)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_2.addWidget(self.checkBox_6, 2, 1, 1, 1)
        self.checkBox_Shutdown = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Shutdown.setEnabled(True)
        self.checkBox_Shutdown.setObjectName("checkBox_Shutdown")
        self.gridLayout_2.addWidget(self.checkBox_Shutdown, 3, 0, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_7.setEnabled(False)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout_2.addWidget(self.checkBox_7, 3, 1, 1, 1)
        self.checkBox_Log = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Log.setEnabled(True)
        self.checkBox_Log.setCheckable(True)
        self.checkBox_Log.setChecked(True)
        self.checkBox_Log.setObjectName("checkBox_Log")
        self.gridLayout_2.addWidget(self.checkBox_Log, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.textBrowser_FilesX = QtWidgets.QTextBrowser(self.tab_3)
        self.textBrowser_FilesX.setGeometry(QtCore.QRect(160, 30, 381, 101))
        self.textBrowser_FilesX.setObjectName("textBrowser_FilesX")
        self.label_FileTypes = QtWidgets.QLabel(self.tab_3)
        self.label_FileTypes.setGeometry(QtCore.QRect(40, 10, 61, 16))
        self.label_FileTypes.setObjectName("label_FileTypes")
        self.textEdit_FileTypesX = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_FileTypesX.setGeometry(QtCore.QRect(3, 30, 141, 271))
        self.textEdit_FileTypesX.setObjectName("textEdit_FileTypesX")
        self.textBrowser_FoldersX = QtWidgets.QTextBrowser(self.tab_3)
        self.textBrowser_FoldersX.setGeometry(QtCore.QRect(160, 170, 381, 101))
        self.textBrowser_FoldersX.setObjectName("textBrowser_FoldersX")
        self.label_Files = QtWidgets.QLabel(self.tab_3)
        self.label_Files.setGeometry(QtCore.QRect(160, 10, 56, 17))
        self.label_Files.setObjectName("label_Files")
        self.label_Folders = QtWidgets.QLabel(self.tab_3)
        self.label_Folders.setGeometry(QtCore.QRect(160, 150, 56, 17))
        self.label_Folders.setObjectName("label_Folders")
        self.pushButton_FilesX = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_FilesX.setGeometry(QtCore.QRect(450, 0, 86, 29))
        self.pushButton_FilesX.setObjectName("pushButton_FilesX")
        self.pushButton_FoldersX = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_FoldersX.setGeometry(QtCore.QRect(450, 140, 86, 29))
        self.pushButton_FoldersX.setObjectName("pushButton_FoldersX")
        self.label_Max = QtWidgets.QLabel(self.tab_3)
        self.label_Max.setGeometry(QtCore.QRect(260, 295, 121, 17))
        self.label_Max.setObjectName("label_Max")
        self.plainTextEdit_FSize = QtWidgets.QPlainTextEdit(self.tab_3)
        self.plainTextEdit_FSize.setGeometry(QtCore.QRect(390, 290, 104, 25))
        self.plainTextEdit_FSize.setObjectName("plainTextEdit_FSize")
        self.label_MaxMB = QtWidgets.QLabel(self.tab_3)
        self.label_MaxMB.setGeometry(QtCore.QRect(505, 295, 31, 20))
        self.label_MaxMB.setObjectName("label_MaxMB")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 572, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAbout_Qt = QtWidgets.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.actionCheckUp = QtWidgets.QAction(MainWindow)
        self.actionCheckUp.setObjectName("actionCheckUp")
        self.actionOpen_Log = QtWidgets.QAction(MainWindow)
        self.actionOpen_Log.setObjectName("actionOpen_Log")
        self.menuFile.addAction(self.actionOpen_Log)
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionCheckUp)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionAbout_Qt)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Source.setText(_translate("MainWindow", "Source"))
        self.pushButton_SB.setText(_translate("MainWindow", "Browse"))
        self.pushButton_DB.setText(_translate("MainWindow", "Browse"))
        self.labels_Destination.setText(_translate("MainWindow", "Destination"))
        self.pushButton_Abort.setText(_translate("MainWindow", "Abort"))
        self.pushButton_OK.setText(_translate("MainWindow", "OK"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Home"))
        self.checkBox_Mir.setToolTip(_translate("MainWindow", "<html><head/><body><p>Mirror the source onto the destination: Copy new files/changes and delete files that are no longer present in the source.</p><p>LEAVE ENABLED FOR NOW!</p></body></html>"))
        self.checkBox_Mir.setText(_translate("MainWindow", "Mirror"))
        self.checkBox_Skip.setToolTip(_translate("MainWindow", "<html><head/><body><p>Skip if a file fails to copy.</p><p>It\'s best to leave this enabled or the robocopy algorithm will be hung up on a .dat file and continue trying to save the file for 500,000 seconds.</p></body></html>"))
        self.checkBox_Skip.setText(_translate("MainWindow", "Skip on fail"))
        self.checkBox_Verb.setToolTip(_translate("MainWindow", "<html><head/><body><p>Show output in a command prompt window.</p><p>Disabled for now.</p></body></html>"))
        self.checkBox_Verb.setText(_translate("MainWindow", "Verbose"))
        self.checkBox_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>empty</p></body></html>"))
        self.checkBox_3.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_6.setToolTip(_translate("MainWindow", "<html><head/><body><p>empty</p></body></html>"))
        self.checkBox_6.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_Shutdown.setToolTip(_translate("MainWindow", "<html><head/><body><p>Shutdown the computer 15 seconds after Argo finishes the backup.</p></body></html>"))
        self.checkBox_Shutdown.setText(_translate("MainWindow", "Shutdown"))
        self.checkBox_7.setToolTip(_translate("MainWindow", "<html><head/><body><p>empty</p></body></html>"))
        self.checkBox_7.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_Log.setToolTip(_translate("MainWindow", "<html><head/><body><p>Log output to Argo.log in your home folder.</p></body></html>"))
        self.checkBox_Log.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.checkBox_Log.setText(_translate("MainWindow", "Log"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Options"))
        self.label_FileTypes.setText(_translate("MainWindow", "File Types"))
        self.label_Files.setText(_translate("MainWindow", "Files"))
        self.label_Folders.setText(_translate("MainWindow", "Folders"))
        self.pushButton_FilesX.setText(_translate("MainWindow", "Browse"))
        self.pushButton_FoldersX.setText(_translate("MainWindow", "Browse"))
        self.label_Max.setText(_translate("MainWindow", "Maximum File Size:"))
        self.label_MaxMB.setText(_translate("MainWindow", "MB"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Exclusions"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout_Qt.setText(_translate("MainWindow", "About Qt"))
        self.actionCheckUp.setText(_translate("MainWindow", "Check for Update"))
        self.actionOpen_Log.setText(_translate("MainWindow", "Open Log"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

